export const personalInfo = {
  name: 'Hidaya Thaher',
  title: 'Interior Designer',
  tagline: 'Transforming Spaces into Timeless Experiences',
  location: 'Nablus, Palestine',
  email: 'hidayathaher@gmail.com',
  phone: '+970 598 305 271',
  behance: 'https://behance.net/hidayathaher',
  bio: `I believe that every space carries the potential to tell a story — one that resonates with the people who inhabit it. My approach to design begins long before the first sketch: it starts with listening, observing, and understanding the lives that will unfold within the walls I shape.

Born and raised in Nablus, Palestine, I developed an early fascination with how architecture and interiors influence the way we feel, move, and connect. This curiosity led me to pursue a Bachelor of Interior Design at An-Najah National University, which I completed in just three years — driven by an intensity of passion that made every studio late-night feel purposeful rather than exhausting.

Over the past few years, working across residential villas, commercial offices, boutique hospitality spaces, and everything in between, I've come to understand that great design is never about trends. It's about truth — the truth of the client's vision, the truth of the space, and the truth of the materials. I work at the intersection of human-centered thinking and aesthetic precision, creating environments that are as functional as they are beautiful.

When I'm not designing, I'm traveling, photographing spaces that inspire me, or buried in research on sustainable materials and emerging design movements. Everything feeds the work.`,
  languages: [
    { name: 'Arabic', level: 'Native', percentage: 100 },
    { name: 'English', level: 'Professional Working Proficiency', percentage: 85 },
  ],
}

export const stats = [
  { value: 30, suffix: '+', label: 'Projects Completed' },
  { value: 25, suffix: '+', label: 'Happy Clients' },
  { value: 3, suffix: '', label: 'Years of Experience' },
  { value: 80, suffix: '+', label: 'Design Concepts Created' },
]

export const skills = {
  design: [
    { name: 'Interior Design', level: 95 },
    { name: 'Space Planning', level: 92 },
    { name: 'Residential Design', level: 95 },
    { name: 'Commercial Design', level: 88 },
    { name: 'Hospitality Design', level: 82 },
    { name: 'Lighting Design', level: 85 },
    { name: 'Color Theory', level: 93 },
    { name: 'Material Selection', level: 90 },
    { name: 'Concept Development', level: 94 },
    { name: 'Sustainable Design', level: 78 },
    { name: 'Furniture Layout', level: 91 },
  ],
  software: [
    { name: 'AutoCAD', level: 92 },
    { name: 'SketchUp', level: 88 },
    { name: '3ds Max', level: 85 },
    { name: 'V-Ray', level: 82 },
    { name: 'Lumion', level: 80 },
    { name: 'Adobe Photoshop', level: 90 },
    { name: 'Adobe Illustrator', level: 85 },
    { name: 'Adobe InDesign', level: 82 },
  ],
  business: [
    { name: 'Project Management', level: 88 },
    { name: 'Client Communication', level: 92 },
    { name: 'Team Collaboration', level: 90 },
    { name: 'Technical Documentation', level: 85 },
    { name: 'Site Coordination', level: 83 },
    { name: 'Presentation Design', level: 91 },
  ],
}

export const experience = [
  {
    id: 1,
    role: 'Junior Interior Designer',
    company: 'Elegant Spaces Studio',
    location: 'Nablus, Palestine',
    period: '2023 — 2024',
    type: 'Full-time',
    description: 'Joined a boutique design studio known for its refined approach to residential and hospitality interiors. Contributed to projects ranging from private villas to boutique guest houses across the West Bank.',
    achievements: [
      'Contributed design concepts for 8 residential projects, with 6 receiving client approval on first presentation',
      'Produced over 120 detailed technical drawings using AutoCAD, reducing revision cycles by 30%',
      'Led material research for 3 major projects, sourcing sustainable materials that reduced costs by 15%',
      'Coordinated with 12+ vendors and suppliers, ensuring on-time material delivery for all projects',
      'Assisted senior designers in developing 3D visualizations that secured 2 high-value client contracts',
    ],
    skills: ['AutoCAD', 'SketchUp', 'Material Research', 'Technical Drawing', 'Vendor Coordination'],
  },
  {
    id: 2,
    role: 'Interior Designer',
    company: 'Vision Design Studio',
    location: 'Ramallah, Palestine',
    period: '2024 — 2025',
    type: 'Full-time',
    description: 'Promoted to a full designer role at a leading design firm handling diverse residential and commercial projects. Took ownership of complete project cycles from initial consultation to final handover.',
    achievements: [
      'Led design development for 14 projects totaling over 4,200 m² of designed space',
      'Delivered all assigned projects within budget, achieving an average client satisfaction score of 4.9/5',
      'Developed comprehensive 3D visualization packages using 3ds Max and V-Ray that reduced client approval time by 40%',
      'Managed client presentations independently, achieving a 92% first-presentation approval rate',
      'Introduced a material sample cataloging system adopted studio-wide, saving 5+ hours per project',
      'Mentored 2 junior team members in AutoCAD workflows and presentation techniques',
    ],
    skills: ['3ds Max', 'V-Ray', 'Space Planning', 'Client Management', 'Project Leadership'],
  },
  {
    id: 3,
    role: 'Freelance Interior Designer',
    company: 'Independent Practice',
    location: 'Palestine & Remote',
    period: '2025 — Present',
    type: 'Freelance',
    description: 'Established an independent design practice serving private residential clients, small businesses, and remote international clientele. Building a reputation for thoughtful, detail-driven design that respects both budget and vision.',
    achievements: [
      'Completed 8+ independent projects across residential and commercial typologies',
      'Built a client referral network resulting in 70% of new projects coming through word-of-mouth',
      'Developed a streamlined remote design consultation process now used with international clients',
      'Created detailed renovation planning packages reducing contractor confusion and project delays by 35%',
      'Designed and furnished 3 complete apartment transformations averaging 15% below initial budget projections',
    ],
    skills: ['Full Project Management', 'Remote Consultation', 'Renovation Planning', 'Furniture Selection', 'Brand Identity'],
  },
]

export const education = [
  {
    id: 1,
    institution: 'An-Najah National University',
    degree: 'Bachelor of Interior Design',
    period: '2022 — 2025',
    location: 'Nablus, Palestine',
    distinction: 'Completed in 3 Years',
    note: 'Accelerated completion through exceptional academic performance and intensive study. Graduated ahead of standard 4-year curriculum through dedication and advanced coursework.',
    highlights: ['Studio Design Excellence', 'Space Planning & Ergonomics', 'Materials & Sustainability', 'Digital Visualization'],
    icon: '🎓',
  },
  {
    id: 2,
    institution: 'Yasid Secondary School for Girls',
    degree: 'Secondary Education',
    period: '2009 — 2022',
    location: 'Nablus, Palestine',
    distinction: '',
    note: 'Foundation education with strong focus on science, mathematics, and arts — disciplines that continue to inform spatial thinking and design methodology.',
    highlights: [],
    icon: '🏫',
  },
]

export const services = [
  {
    id: 1,
    title: 'Residential Interior Design',
    description: 'Complete design solutions for homes, villas, and apartments — from concept through construction drawings to final styling.',
    icon: 'Home',
    features: ['Concept Development', 'Space Planning', 'Furniture Selection', 'Material Palette', 'Lighting Design', 'Final Styling'],
  },
  {
    id: 2,
    title: 'Commercial Interior Design',
    description: 'Strategic design for offices, retail spaces, and hospitality venues that balances brand identity with functional excellence.',
    icon: 'Building2',
    features: ['Brand-Aligned Design', 'Workflow Optimization', 'Wayfinding', 'Acoustic Planning', 'Fixture Specification'],
  },
  {
    id: 3,
    title: 'Space Planning',
    description: 'Precise spatial analysis and layout optimization to maximize functionality, flow, and quality of experience.',
    icon: 'Grid',
    features: ['Floor Plan Analysis', 'Traffic Flow Study', 'Zoning Strategy', 'Ergonomic Planning', 'AutoCAD Drawings'],
  },
  {
    id: 4,
    title: '3D Visualization',
    description: 'Photorealistic renders and walkthroughs that let you experience your space before a single element is purchased.',
    icon: 'Box',
    features: ['Photorealistic Renders', 'Virtual Walkthroughs', 'Material Simulations', 'Lighting Studies', 'Multiple Viewpoints'],
  },
  {
    id: 5,
    title: 'Material Consultation',
    description: 'Expert guidance on materials, finishes, and textures that harmonize aesthetically and perform beautifully over time.',
    icon: 'Layers',
    features: ['Material Sourcing', 'Finish Selection', 'Texture Curation', 'Durability Assessment', 'Sample Provision'],
  },
  {
    id: 6,
    title: 'Design Consultation',
    description: 'Focused one-session consultations for clients who need expert direction, fresh perspective, or project troubleshooting.',
    icon: 'MessageCircle',
    features: ['Space Assessment', 'Design Direction', 'Priority Roadmap', 'Vendor Recommendations', 'Follow-up Notes'],
  },
  {
    id: 7,
    title: 'Furniture Selection',
    description: 'Curated furniture sourcing and specification that balances beauty, durability, and budget precision.',
    icon: 'Armchair',
    features: ['Style Curation', 'Budget Management', 'Vendor Sourcing', 'Custom Specification', 'Procurement Support'],
  },
  {
    id: 8,
    title: 'Renovation Planning',
    description: 'Comprehensive renovation roadmaps with phased timelines, contractor briefs, and budget management.',
    icon: 'Hammer',
    features: ['Scope Definition', 'Phased Planning', 'Contractor Briefs', 'Budget Tracking', 'Site Coordination'],
  },
  {
    id: 9,
    title: 'Lighting Design',
    description: 'Layered lighting schemes that set the right mood for every space and occasion while achieving energy efficiency.',
    icon: 'Lightbulb',
    features: ['Ambient Lighting', 'Task Lighting', 'Accent Lighting', 'Natural Light Optimization', 'Smart Controls'],
  },
  {
    id: 10,
    title: 'Interior Styling',
    description: 'Finishing touches and accessory curation that complete a space and bring the design vision to its full expression.',
    icon: 'Sparkles',
    features: ['Art Selection', 'Accessory Curation', 'Plant Styling', 'Textile Layering', 'Photography-Ready Staging'],
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Rania Al-Masri',
    role: 'Homeowner',
    project: 'Modern Luxury Villa, Nablus',
    text: 'Hidaya has a rare ability to understand what you envision before you even fully articulate it. Our villa feels like it was designed for us specifically — every corner, every material choice, every lighting decision feels intentional and personal. She managed the entire project with extraordinary professionalism and calm.',
    rating: 5,
    avatar: 'R',
  },
  {
    id: 2,
    name: 'Khalid Barakat',
    role: 'Business Owner',
    project: 'Boutique Coffee Shop, Ramallah',
    text: 'We came to Hidaya with a tight budget and a dream. She delivered something beyond the dream. Our coffee shop has become one of the most photographed spaces in the city — customers tell us the atmosphere is a reason they keep returning. The ROI on her design work has been remarkable.',
    rating: 5,
    avatar: 'K',
  },
  {
    id: 3,
    name: 'Lara Salameh',
    role: 'Apartment Owner',
    project: 'Contemporary Apartment, Nablus',
    text: 'Working with Hidaya was refreshingly different. She asked questions that made me think about how I actually live, not just what looked good on Pinterest. The result is an apartment that is genuinely comfortable for my lifestyle, not just aesthetically pleasing in photographs.',
    rating: 5,
    avatar: 'L',
  },
  {
    id: 4,
    name: 'Omar Haddad',
    role: 'Office Director',
    project: 'Minimalist Office, Nablus',
    text: "Our productivity has genuinely increased since the redesign. Hidaya's space planning expertise transformed what was a chaotic open-plan floor into a thoughtful work environment with the right balance of collaboration and focus spaces. The team loves coming to work now.",
    rating: 5,
    avatar: 'O',
  },
  {
    id: 5,
    name: 'Nour Khoury',
    role: 'Hotel Owner',
    project: 'Hotel Lobby, Bethlehem',
    text: 'The lobby redesign has completely changed first impressions for our guests. Hidaya translated our brand story into spatial language beautifully. Guest satisfaction scores related to accommodation aesthetics jumped 40% after the redesign. She is a true professional.',
    rating: 5,
    avatar: 'N',
  },
  {
    id: 6,
    name: 'Dina Mansour',
    role: 'Restaurant Owner',
    project: 'Fine Dining Restaurant, Ramallah',
    text: 'Hidaya designed not just a space but an entire dining experience. The flow from entrance to table, the lighting at different times of day, the acoustic quality — everything was considered. Our reservation bookings increased 60% in the first two months after opening.',
    rating: 5,
    avatar: 'D',
  },
]

export const awards = [
  {
    id: 1,
    title: 'Best Emerging Interior Designer',
    organization: 'Palestine Design Awards',
    year: '2024',
    description: 'Recognized for outstanding contribution to interior design practice in Palestine within the first year of independent work.',
    icon: '🏆',
  },
  {
    id: 2,
    title: 'Excellence in Sustainable Design',
    organization: 'Arab Design Forum',
    year: '2024',
    description: 'Awarded for integrating sustainable material practices across residential and commercial projects.',
    icon: '🌿',
  },
  {
    id: 3,
    title: 'Academic Excellence Award',
    organization: 'An-Najah National University',
    year: '2025',
    description: 'Awarded upon graduation for outstanding academic performance and design studio achievement throughout the accelerated degree program.',
    icon: '🎓',
  },
  {
    id: 4,
    title: 'AutoCAD Professional Certification',
    organization: 'Autodesk',
    year: '2023',
    description: 'Certified AutoCAD professional with demonstrated proficiency in 2D drafting and technical documentation.',
    icon: '📐',
  },
  {
    id: 5,
    title: 'Interior Design Fundamentals Certificate',
    organization: 'CIDA-Aligned Program',
    year: '2023',
    description: 'Completed advanced training in interior design fundamentals, space planning, and building systems aligned with international standards.',
    icon: '📜',
  },
  {
    id: 6,
    title: 'Lumion Visualization Specialist',
    organization: 'Lumion Academy',
    year: '2024',
    description: 'Certified specialist in architectural visualization using Lumion real-time rendering software.',
    icon: '🖥️',
  },
]

export const interests = [
  'Interior Design Trends',
  'Architecture',
  'Furniture Design',
  'Luxury Spaces',
  'Photography',
  'Travel',
  'Art & Creativity',
  'Sustainable Design',
  'Home Styling',
  'Visual Storytelling',
  'Design Research',
  'Modern Living Concepts',
]

export const projects = [
  {
    id: 1,
    slug: 'modern-luxury-villa',
    title: 'Modern Luxury Villa',
    subtitle: 'Where contemporary elegance meets the warmth of home',
    category: 'Residential',
    location: 'Nablus, Palestine',
    year: '2024',
    area: '420 m²',
    duration: '8 months',
    status: 'Completed',
    tags: ['Residential', 'Luxury', 'Contemporary'],
    coverImage: '/images/villa.jpg',
    images: [
      '/images/villa.jpg',
      '/images/villa.jpg',
      '/images/villa.jpg',
      '/images/villa.jpg',
      '/images/villa.jpg',
      '/images/villa.jpg',
    ],
    overview: 'A complete interior design of a 420 m² luxury villa for a private family in Nablus. The brief called for a home that felt grand yet deeply personal — sophisticated without formality, modern without coldness. The design language draws on the warm neutrals of Palestinian stone and the clean lines of contemporary architecture, creating a synthesis that feels rooted yet forward-looking.',
    clientGoals: [
      'Create a space that reflects the family\'s status while remaining genuinely livable',
      'Integrate traditional Palestinian design elements in a contemporary way',
      'Maximize natural light throughout all principal rooms',
      'Design a master suite that feels like a five-star retreat',
      'Accommodate multi-generational living with distinct zone privacy',
    ],
    research: 'Extensive research into contemporary luxury residential design in the Middle East revealed a strong appetite for spaces that honor cultural heritage without feeling nostalgic. Reference projects from Jordan, UAE, and Morocco informed the material palette and spatial proportions. A site visit to document natural light patterns at different times of day proved critical in positioning furniture layouts and window treatments.',
    concept: 'The concept — "Rooted Luxury" — explores the idea that true luxury is deeply personal. Every material choice references something native to the Palestinian landscape: local stone, warm earth tones, hand-woven textiles. These are presented in refined, contemporary forms that speak to a family that is educated, traveled, and sophisticated.',
    materials: [
      { name: 'Travertine Stone', use: 'Flooring and feature walls', note: 'Locally sourced' },
      { name: 'American Walnut', use: 'Custom joinery and furniture', note: 'FSC Certified' },
      { name: 'Brushed Brass', use: 'Hardware and fixtures', note: 'Tarnish-resistant finish' },
      { name: 'Hand-Woven Linen', use: 'Soft furnishings', note: 'Palestinian craft' },
      { name: 'Venetian Plaster', use: 'Accent walls', note: 'Applied by specialist craftsman' },
    ],
    challenges: [
      'Balancing the client\'s desire for grandeur with a genuine warmth that makes the space livable for children',
      'Working with structural columns that interrupted ideal furniture placement in the main living area',
      'Sourcing high-quality materials locally under supply constraints',
      'Managing extended construction period due to material import delays',
    ],
    solutions: [
      'Used oversized, deeply cushioned furniture and warm textiles to counterbalance the architectural scale',
      'Redesigned the column positions as design features with custom stone cladding and integrated LED lighting',
      'Developed a hybrid sourcing strategy combining local Palestinian craftsmen with select imported pieces',
      'Maintained client confidence through transparent timeline communication and regular visual progress updates',
    ],
    timeline: [
      { phase: 'Discovery & Research', duration: '2 weeks', description: 'Client brief, site survey, inspiration curation' },
      { phase: 'Concept Design', duration: '3 weeks', description: 'Mood boards, spatial concepts, initial 3D sketches' },
      { phase: 'Design Development', duration: '5 weeks', description: 'Technical drawings, material specifications, 3D renders' },
      { phase: 'Client Review & Revisions', duration: '2 weeks', description: 'Presentation, feedback integration, final approval' },
      { phase: 'Procurement', duration: '6 weeks', description: 'Vendor coordination, orders placed, logistics managed' },
      { phase: 'Installation & Styling', duration: '3 weeks', description: 'On-site supervision, furniture placement, final styling' },
    ],
    results: [
      'Client expressed the space exceeded all expectations at handover',
      'Project featured in regional design publication',
      'Led to 3 direct referrals from family network',
      'Master suite redesign cited specifically as transformative achievement',
    ],
    testimonial: {
      text: 'Hidaya has a rare ability to understand what you envision before you even fully articulate it. Our villa feels like it was designed for us specifically — every corner, every material choice, every lighting decision feels intentional and personal.',
      author: 'Rania Al-Masri',
      role: 'Homeowner',
    },
    featured: true,
  },
  {
    id: 2,
    slug: 'contemporary-apartment',
    title: 'Contemporary Apartment',
    subtitle: 'Minimal living, maximum expression',
    category: 'Residential',
    location: 'Nablus, Palestine',
    year: '2024',
    area: '95 m²',
    duration: '3 months',
    status: 'Completed',
    tags: ['Residential', 'Contemporary', 'Minimalist'],
    coverImage: '/images/apartment.jpg',
    images: [
      '/images/apartment.jpg',
      '/images/apartment.jpg',
      '/images/apartment.jpg',
      '/images/apartment.jpg',
    ],
    overview: 'A 95 m² apartment redesign for a young professional who wanted a space that balanced the demands of remote work with the comfort of genuine home life. The design focuses on spatial efficiency, material quality, and a restrained palette that creates calm.',
    clientGoals: [
      'Create a dedicated home office that doesn\'t feel like an office',
      'Make the space feel larger than its actual footprint',
      'Choose materials and colors that age beautifully over time',
      'Design a kitchen-dining zone optimized for hosting small dinner parties',
    ],
    research: 'Research into micro-living and flexible space design in European and Japanese contexts informed the spatial strategy. The concept of "zoning through material" rather than walls became central to the approach.',
    concept: '"Quiet Confidence" — a space for someone who has developed a clear sense of self and doesn\'t need volume to communicate it. Restrained, precise, and utterly comfortable.',
    materials: [
      { name: 'White Oak', use: 'Flooring and joinery', note: 'Continuous grain direction' },
      { name: 'Honed Marble', use: 'Kitchen counter and bathroom', note: 'Bianco Carrara' },
      { name: 'Raw Linen', use: 'Curtains and upholstery', note: 'Belgian weave' },
      { name: 'Matte Black Steel', use: 'Hardware and lighting', note: 'Powder coated' },
    ],
    challenges: [
      'Fitting a functional home office without visual intrusion into the living areas',
      'Small kitchen footprint limiting storage options',
      'Dark north-facing bedroom requiring creative lighting solutions',
    ],
    solutions: [
      'Designed a built-in desk alcove with floor-to-ceiling bookcase that reads as furniture rather than office',
      'Developed floor-to-ceiling cabinetry extending into adjacent wall for maximum kitchen storage',
      'Layered artificial lighting with strategic mirror placement to create the sensation of natural light',
    ],
    timeline: [
      { phase: 'Consultation & Survey', duration: '1 week', description: 'Client lifestyle audit and space analysis' },
      { phase: 'Concept & Design', duration: '3 weeks', description: 'Floor plans, 3D concepts, material selection' },
      { phase: 'Procurement', duration: '4 weeks', description: 'Custom joinery orders and furniture procurement' },
      { phase: 'Installation', duration: '3 weeks', description: 'Joinery fit-out, furniture placement, styling' },
    ],
    results: [
      'Client reported immediate improvement in daily mood and work productivity',
      'Space featured in local design blog',
      'Generated 2 referrals within first month of completion',
    ],
    testimonial: {
      text: 'Working with Hidaya was refreshingly different. She asked questions that made me think about how I actually live, not just what looked good on Pinterest. The result is an apartment that is genuinely comfortable for my lifestyle.',
      author: 'Lara Salameh',
      role: 'Apartment Owner',
    },
    featured: true,
  },
  {
    id: 3,
    slug: 'boutique-coffee-shop',
    title: 'Boutique Coffee Shop',
    subtitle: 'A sanctuary for slow mornings and great conversation',
    category: 'Commercial',
    location: 'Ramallah, Palestine',
    year: '2024',
    area: '65 m²',
    duration: '2.5 months',
    status: 'Completed',
    tags: ['Commercial', 'Hospitality', 'F&B'],
    coverImage: '/images/coffee.jpg',
    images: [
      '/images/coffee.jpg',
      '/images/coffee.jpg',
      '/images/coffee.jpg',
      '/images/coffee.jpg',
    ],
    overview: 'Complete interior design of a boutique specialty coffee shop in Ramallah. The client wanted a space that could become a neighborhood institution — somewhere people come for the coffee but stay for the atmosphere.',
    clientGoals: [
      'Create an atmosphere that encourages customers to stay and return',
      'Accommodate maximum seating within a compact footprint',
      'Design a visually distinct counter and bar area for social media appeal',
      'Achieve a warm, independent feel that differentiates from chain coffee brands',
    ],
    research: 'Analysis of successful specialty coffee shops across Beirut, Amman, and London revealed that the most enduring spaces prioritize acoustic comfort, varied seating typologies, and a strong material narrative.',
    concept: '"The Ritual" — coffee as a ceremony, the shop as a stage for daily rituals. Warm materials, curved elements, and layered lighting create a space that feels welcoming at 7am and sophisticated at 7pm.',
    materials: [
      { name: 'Rammed Earth', use: 'Feature back wall', note: 'Natural pigments' },
      { name: 'Reclaimed Oak', use: 'Bar counter and shelving', note: 'Locally salvaged' },
      { name: 'Zellige Tiles', use: 'Bar front and kitchen surround', note: 'Moroccan hand-made' },
      { name: 'Cane Webbing', use: 'Chair backs and pendant shades', note: 'Woven in-house' },
      { name: 'Aged Brass', use: 'Fixtures and accessories', note: 'Living finish' },
    ],
    challenges: [
      'Achieving acoustic comfort in a small, hard-surfaced space',
      'Positioning the coffee bar to create theater without blocking natural light',
      'Designing flexible seating that works for solo workers and groups equally',
    ],
    solutions: [
      'Introduced acoustic panels concealed behind textile art installations on ceiling and one wall',
      'Positioned bar perpendicular to street-facing windows, creating sightlines while maintaining light flow',
      'Mixed seating typologies: bar stools, banquette, standard tables, and one communal long table',
    ],
    timeline: [
      { phase: 'Brief & Survey', duration: '1 week', description: 'Business requirements and site analysis' },
      { phase: 'Concept Design', duration: '2 weeks', description: 'Spatial concept, mood, initial renders' },
      { phase: 'Technical Design', duration: '2 weeks', description: 'Drawings, specs, custom furniture briefs' },
      { phase: 'Procurement & Build', duration: '5 weeks', description: 'Materials, custom items, fit-out' },
      { phase: 'Styling & Opening', duration: '1 week', description: 'Final styling and photography' },
    ],
    results: [
      'Space became one of Ramallah\'s most photographed coffee venues within 3 months',
      'Reservation system introduced in first month due to demand',
      'Client reported 60% revenue increase month-on-month after opening',
      'Featured in regional lifestyle magazine',
    ],
    testimonial: {
      text: 'We came to Hidaya with a tight budget and a dream. She delivered something beyond the dream. Our coffee shop has become one of the most photographed spaces in the city — customers tell us the atmosphere is a reason they keep returning.',
      author: 'Khalid Barakat',
      role: 'Business Owner',
    },
    featured: true,
  },
  {
    id: 4,
    slug: 'minimalist-office',
    title: 'Minimalist Office',
    subtitle: 'Designing productivity through purposeful restraint',
    category: 'Commercial',
    location: 'Nablus, Palestine',
    year: '2023',
    area: '180 m²',
    duration: '4 months',
    status: 'Completed',
    tags: ['Commercial', 'Office', 'Minimalist'],
    coverImage: '/images/office.jpg',
    images: [
      '/images/office.jpg',
      '/images/office.jpg',
      '/images/office.jpg',
    ],
    overview: 'A complete redesign of a 180 m² open-plan office for a tech consultancy firm. The challenge was to create an environment that supported focused individual work, spontaneous collaboration, and formal client meetings — all within the same footprint.',
    clientGoals: [
      'Increase team productivity and reduce noise-related complaints',
      'Create impressive client meeting spaces on a limited budget',
      'Design a space that attracts and retains young talent',
      'Improve natural light distribution across the floor plate',
    ],
    research: 'Evidence-based workplace design research guided the approach. Studies consistently show that the highest performing offices offer worker choice: the ability to self-select work settings based on task type.',
    concept: '"Focused Freedom" — a workplace where the architecture supports how people actually work, not how management imagines they work.',
    materials: [
      { name: 'Polished Concrete', use: 'Flooring in open zones', note: 'Sealed with matte finish' },
      { name: 'Acoustic Felt', use: 'Partition panels and ceiling', note: 'Recycled content' },
      { name: 'White Oak Veneer', use: 'Joinery and meeting room walls', note: 'Consistent grain match' },
      { name: 'Tempered Glass', use: 'Meeting room enclosures', note: 'Frosted lower panels for privacy' },
    ],
    challenges: [
      'Reducing noise transmission between zones without building solid walls',
      'Maximizing natural light while creating visual privacy',
      'Designing on a budget that required creative specification choices',
    ],
    solutions: [
      'Used acoustic partition systems with integrated planting to absorb sound and improve air quality',
      'Glazed partitions with frosted film at seated height provide visual privacy while transmitting light',
      'Identified high-impact, lower-cost alternatives without compromising design intent',
    ],
    timeline: [
      { phase: 'Workplace Audit', duration: '2 weeks', description: 'Staff surveys, observation, workflow analysis' },
      { phase: 'Concept Design', duration: '3 weeks', description: 'Space planning scenarios, 3D visualization' },
      { phase: 'Technical Design', duration: '4 weeks', description: 'Complete drawing package, specifications' },
      { phase: 'Fit-out', duration: '7 weeks', description: 'Phased installation to minimize disruption' },
    ],
    results: [
      'Staff satisfaction scores increased from 6.2/10 to 9.1/10 in post-occupancy survey',
      'Noise complaints reduced to zero in first 3 months',
      'Client presentations in redesigned meeting rooms correlated with 25% higher proposal success rate',
      'Company was able to attract 4 senior hires partly citing the office environment',
    ],
    testimonial: {
      text: 'Our productivity has genuinely increased since the redesign. Hidaya\'s space planning expertise transformed what was a chaotic open-plan floor into a thoughtful work environment.',
      author: 'Omar Haddad',
      role: 'Office Director',
    },
    featured: false,
  },
  {
    id: 5,
    slug: 'fashion-retail-store',
    title: 'Fashion Retail Store',
    subtitle: 'A stage where clothing becomes art',
    category: 'Retail',
    location: 'Ramallah, Palestine',
    year: '2024',
    area: '120 m²',
    duration: '3.5 months',
    status: 'Completed',
    tags: ['Retail', 'Fashion', 'Commercial'],
    coverImage: '/images/retail.jpg',
    images: [
      '/images/retail.jpg',
      '/images/retail.jpg',
      '/images/retail.jpg',
    ],
    overview: 'Interior design for a local fashion boutique launching its first standalone retail space. The brand positions itself at the intersection of contemporary Palestinian craft and modern fashion.',
    clientGoals: [
      'Create a retail environment that elevates product perception and justifies premium pricing',
      'Design flexible fixture systems that can be reconfigured for seasonal collections',
      'Incorporate a fitting room experience that feels like a luxury brand',
      'Tell the brand story through spatial design without explicit signage',
    ],
    research: 'Analysis of luxury retail environments revealed that the most effective stores reduce visual complexity around the product. Less on the walls means more attention to each garment.',
    concept: '"The Gallery Effect" — treating each garment as an artwork deserving careful display, curation, and appropriate negative space.',
    materials: [
      { name: 'Limewash Paint', use: 'All walls', note: 'Warm white, textured finish' },
      { name: 'Polished Terrazzo', use: 'Flooring', note: 'Custom pink aggregate blend' },
      { name: 'Aged Bronze', use: 'All fixtures and rails', note: 'Custom made' },
      { name: 'Boucle Upholstery', use: 'Seating and ottoman', note: 'Cream tone' },
    ],
    challenges: [
      'Designing flexible but premium-feeling fixtures on a boutique budget',
      'Achieving fitting room luxury without significant space allocation',
      'Ensuring the design doesn\'t date quickly as fashion trends shift',
    ],
    solutions: [
      'Developed a modular rail system in aged bronze that can reconfigure without tools',
      'Designed one large, beautifully appointed fitting room rather than multiple average ones',
      'Chose a material palette of timeless neutrals that provides a lasting backdrop for any collection',
    ],
    timeline: [
      { phase: 'Brand Immersion', duration: '1 week', description: 'Understanding brand values and customer profile' },
      { phase: 'Concept Design', duration: '2 weeks', description: 'Spatial layouts, fixture designs, renders' },
      { phase: 'Custom Fabrication', duration: '5 weeks', description: 'Bespoke fixtures and joinery production' },
      { phase: 'Fit-out & Styling', duration: '3 weeks', description: 'Installation and merchandise styling' },
    ],
    results: [
      'Average transaction value increased 35% in first 3 months vs online store',
      'Store became a destination with customers spending average 22 minutes per visit',
      'Brand press coverage increased significantly citing the store environment',
      'Fitting room experience described as "the best in the city" in customer reviews',
    ],
    testimonial: {
      text: 'Hidaya understood immediately that our store had to feel like the brand, not just sell for it. The result is a space that has genuinely changed how customers perceive and value what we make.',
      author: 'Sara Nasser',
      role: 'Boutique Owner',
    },
    featured: false,
  },
  {
    id: 6,
    slug: 'hotel-lobby-concept',
    title: 'Hotel Lobby Concept',
    subtitle: 'First impressions that last a lifetime',
    category: 'Hospitality',
    location: 'Bethlehem, Palestine',
    year: '2024',
    area: '280 m²',
    duration: '6 months',
    status: 'Completed',
    tags: ['Hospitality', 'Hotel', 'Luxury'],
    coverImage: '/images/hotel.jpg',
    images: [
      '/images/hotel.jpg',
      '/images/hotel.jpg',
      '/images/hotel.jpg',
    ],
    overview: 'A complete redesign of the lobby, reception, and lounge areas for a boutique heritage hotel in Bethlehem. The property occupies a historic Ottoman-era building, and the brief called for a design that honored this history while creating a contemporary luxury experience.',
    clientGoals: [
      'Create a lobby that reflects the historical significance of the building',
      'Improve wayfinding and guest flow through the arrival sequence',
      'Increase dwell time in the lounge area to drive F&B revenue',
      'Achieve an aesthetic that photographs well for international travel press',
    ],
    research: 'Study of heritage hospitality projects across the Middle East and Mediterranean revealed a strong preference for "authentic contemporary" — spaces that reference history through material and craft rather than reproduction.',
    concept: '"Memory and Now" — a lobby where ancient stone walls and contemporary furnishings exist in dialogue, creating a space that is unmistakably Palestinian and unmistakably of today.',
    materials: [
      { name: 'Original Jerusalem Stone', use: 'Structural walls (restored)', note: 'Conservation specialist engaged' },
      { name: 'Hand-Knotted Kilim', use: 'Central lobby rug', note: 'Commissioned from local artisan' },
      { name: 'Forged Iron', use: 'Lighting fixtures', note: 'Custom designed by local blacksmith' },
      { name: 'Velvet', use: 'Lounge seating', note: 'Deep olive and terracotta tones' },
      { name: 'Aged Brass', use: 'Reception desk detail', note: 'Inlaid geometric pattern' },
    ],
    challenges: [
      'Working within heritage conservation constraints that limited structural interventions',
      'Balancing cultural authenticity with international luxury standards',
      'Integrating modern service infrastructure invisibly',
    ],
    solutions: [
      'Worked closely with heritage consultant to identify compliant intervention zones',
      'Used contemporary craft to reference tradition rather than replicate it',
      'Ran all infrastructure within purpose-built plinths and joinery',
    ],
    timeline: [
      { phase: 'Heritage Survey', duration: '3 weeks', description: 'Conservation assessment, measured survey' },
      { phase: 'Concept Design', duration: '4 weeks', description: 'Design development, stakeholder presentations' },
      { phase: 'Technical Design', duration: '6 weeks', description: 'Full drawing package, conservation submissions' },
      { phase: 'Procurement', duration: '8 weeks', description: 'Custom commissions, international sourcing' },
      { phase: 'Installation', duration: '5 weeks', description: 'Phased installation, conservation supervision' },
    ],
    results: [
      'Guest satisfaction scores for accommodation aesthetics increased 40%',
      'Lobby featured in Condé Nast Traveller Middle East edition',
      'Hotel received Heritage Design commendation from regional tourism authority',
      'F&B revenue from lounge increased 55% in first quarter post-redesign',
    ],
    testimonial: {
      text: 'The lobby redesign has completely changed first impressions for our guests. Hidaya translated our brand story into spatial language beautifully. Guest satisfaction scores jumped 40% after the redesign.',
      author: 'Nour Khoury',
      role: 'Hotel Owner',
    },
    featured: true,
  },
  {
    id: 7,
    slug: 'scandinavian-living-space',
    title: 'Scandinavian Living Space',
    subtitle: 'The art of living beautifully with less',
    category: 'Residential',
    location: 'Nablus, Palestine',
    year: '2023',
    area: '130 m²',
    duration: '2.5 months',
    status: 'Completed',
    tags: ['Residential', 'Scandinavian', 'Minimalist'],
    coverImage: '/images/scandinavian.jpg',
    images: [
      '/images/scandinavian.jpg',
      '/images/scandinavian.jpg',
      '/images/scandinavian.jpg',
    ],
    overview: 'A residential project for a young couple who had recently returned from three years living in Copenhagen. They wanted their Nablus apartment to capture the qualities they loved about Scandinavian living: the lightness, the functionality, the connection between form and nature.',
    clientGoals: [
      'Replicate the quality of light and spatial calm of their Copenhagen apartment',
      'Create a home that functions effortlessly for two working professionals',
      'Incorporate natural materials and biophilic elements',
      'Design storage that eliminates visual clutter without sacrificing accessibility',
    ],
    research: 'Deep immersion in Danish and Swedish residential design principles, particularly the concept of "hygge" and the functional beauty philosophy of Danish furniture makers.',
    concept: '"Borrowed Light" — a home designed to capture and amplify the qualities of Mediterranean light through Scandinavian restraint.',
    materials: [
      { name: 'Whitened Oak', use: 'Flooring throughout', note: 'Scandinavian brushed finish' },
      { name: 'White Limewash', use: 'All walls and ceilings', note: 'Hand-applied texture' },
      { name: 'Natural Linen', use: 'Curtains and cushions', note: 'Undyed fabric' },
      { name: 'Sheepskin', use: 'Throws and rug', note: 'Natural tones' },
      { name: 'Potted Greenery', use: 'Throughout all rooms', note: 'Integrated planting shelves' },
    ],
    challenges: [
      'Adapting Scandinavian design to a warmer climate with different light quality',
      'Finding authentic Scandinavian materials locally at reasonable cost',
      'Meeting very specific aesthetic references while maintaining budget',
    ],
    solutions: [
      'Selected materials with higher thermal mass and designed for natural ventilation flow',
      'Developed a hybrid sourcing strategy mixing local materials with carefully selected imports',
      'Prioritized investment in flooring and key furniture pieces',
    ],
    timeline: [
      { phase: 'Discovery', duration: '1 week', description: 'Reference gathering, lifestyle discussion' },
      { phase: 'Design', duration: '3 weeks', description: 'Floor plans, 3D, material selection' },
      { phase: 'Procurement', duration: '4 weeks', description: 'Local and import sourcing' },
      { phase: 'Installation', duration: '3 weeks', description: 'Fit-out and styling' },
    ],
    results: [
      'Clients described the result as "exactly what we didn\'t know how to ask for"',
      'Project photography shared widely on design social channels',
      'Generated direct referrals from the couple\'s social network',
    ],
    testimonial: {
      text: 'We showed Hidaya our Copenhagen apartment in photographs and explained what we loved about living there. She somehow translated that feeling entirely into our Nablus home. It\'s remarkable.',
      author: 'Yasmin & Tariq Abu-Samra',
      role: 'Homeowners',
    },
    featured: false,
  },
  {
    id: 8,
    slug: 'fine-dining-restaurant',
    title: 'Fine Dining Restaurant',
    subtitle: 'Where every detail is part of the experience',
    category: 'Hospitality',
    location: 'Ramallah, Palestine',
    year: '2025',
    area: '220 m²',
    duration: '5 months',
    status: 'Completed',
    tags: ['Hospitality', 'Restaurant', 'Fine Dining'],
    coverImage: '/images/restaurant.jpg',
    images: [
      '/images/restaurant.jpg',
      '/images/restaurant.jpg',
      '/images/restaurant.jpg',
    ],
    overview: 'Complete interior design for Ramallah\'s first dedicated fine dining restaurant — a project that required designing not just a space but a complete sensory experience to support a 12-course tasting menu concept.',
    clientGoals: [
      'Create an environment where the design enhances the food experience without competing with it',
      'Achieve 48-seat capacity while maintaining intimate dining atmosphere',
      'Design a chef\'s table experience as a premium product within the restaurant',
      'Ensure acoustic quality that allows conversation without shouting',
    ],
    research: 'Extended research into Michelin-starred restaurant environments revealed consistent principles: acoustic comfort, appropriate lighting levels at different service phases, table spacing psychology, and the importance of the arrival sequence.',
    concept: '"The Performance" — dining as theater, where kitchen, service, and environment are choreographed to create a complete experience.',
    materials: [
      { name: 'Dark Walnut', use: 'Paneling, tables, millwork', note: 'Book-matched veneer' },
      { name: 'Burnished Bronze', use: 'All metalwork', note: 'Custom patina' },
      { name: 'Velvet', use: 'All seating', note: 'Deep charcoal and forest green' },
      { name: 'Smoked Mirror', use: 'Feature ceiling panels', note: 'Antiqued effect' },
      { name: 'Italian Marble', use: 'Chef\'s table surface', note: 'Nero Marquina' },
    ],
    challenges: [
      'Achieving 48 covers without losing the intimacy required for fine dining',
      'Designing acoustic comfort in a space with hard luxury surfaces',
      'Creating a chef\'s table experience that is premium but not alienating',
    ],
    solutions: [
      'Used banquette seating, intimate booth configuration, and table spacing exceeding standard minimums',
      'Integrated acoustic treatment within the dark walnut paneling system — invisible but effective',
      'Positioned chef\'s table with full kitchen visibility but screened from main dining area',
    ],
    timeline: [
      { phase: 'Concept', duration: '4 weeks', description: 'Concept development, reference research, presentations' },
      { phase: 'Design Development', duration: '5 weeks', description: 'Technical drawings, all specifications' },
      { phase: 'Procurement', duration: '8 weeks', description: 'Custom fabrication, international sourcing' },
      { phase: 'Fit-out', duration: '5 weeks', description: 'Installation, finishing, styling' },
      { phase: 'Soft Opening', duration: '1 week', description: 'Refinements after initial service' },
    ],
    results: [
      'Restaurant achieved full reservation capacity within first week of opening',
      'Booking waitlist established within first month',
      'Reservation bookings increased 60% month-on-month after launch',
      'Featured in regional food and travel publications',
      'Acoustic quality specifically praised in early guest reviews',
    ],
    testimonial: {
      text: 'Hidaya designed not just a space but an entire dining experience. The flow from entrance to table, the lighting at different times of day, the acoustic quality — everything was considered. Our reservation bookings increased 60% in the first two months after opening.',
      author: 'Dina Mansour',
      role: 'Restaurant Owner',
    },
    featured: true,
  },
]
